<script>
  
</script>

<div class="sc-hcupDf fkQdDC"><div class="item">
   <h2>Privacy Policy</h2>
   <p>
     You hereby acknowledge and accept that if we deem necessary, we are able to
     collect and otherwise use your personal data in order to allow you access
     and use of the Websites and in order to allow you to participate in the
     Games.
   </p>
   <p>
     We hereby acknowledge that in collecting your personal details as stated in
     the previous provision, we are bound by the Data Protection Act. We will
     protect your personal information and respect your privacy in accordance
     with best business practices and applicable laws.
   </p>
   <p>
     We will use your personal data to allow you to participate in the Games and
     to carry out operations relevant to your participation in the Games. We may
     also use your personal data to inform you of changes, new services and
     promotions that we think you may find interesting. If you do not wish to
     receive such direct marketing correspondences, you may opt out of the
     service.
   </p>
   <p>
     Your personal data will not be disclosed to third parties, unless it is
     required by law. As NANOGAMES.IO business partners or suppliers or service
     providers may be responsible for certain parts of the overall functioning or
     operation of the Website, personal data may be disclosed to them. The
     employees of NANOGAMES.IO have access to your personal data for the purpose of
     executing their duties and providing you with the best possible assistance
     and service. You hereby consent to such disclosures.
   </p>
   <p>
     We shall keep all information provided as personal data. You have the right
     to access personal data held by us about you. No data shall be destroyed
     unless required by law, or unless the information held is no longer required
     to be kept for the purpose of the relationship.
   </p>
   <p>
     In order to make your visit to the Websites more user-friendly, to keep
     track of visits to the Websites and to improve the service, we collect a
     small piece of information sent from your browser, called a cookie. You can,
     if you wish, turn off the collection of cookies. You must note, however,
     that turning off cookies may severely restrict or completely hinder your use
     of the Websites.
   </p>
 
   <h2 classname="cookie">Cookies Policy</h2>
   <p class="em">1.What are cookies?</p>
   <p>
     A cookie is a piece of information in the form of a very small text file
     that is placed on an internet user's computer. It is generated by a web page
     server (which is basically the computer that operates the website) and can
     be used by that server whenever the user visits the site. A cookie can be
     thought of as an internet user's identification card, which tells a website
     when the user has returned. Cookies can't harm your computer and we don't
     store any personally identifiable information about you on any of our
     cookies.
   </p>
   <p class="em">2.Why do we use cookies on NANOGAMES.IO?</p>
   <p>
     NANOGAMES.IO uses two types of cookies: cookies set by us and cookies set by
     third parties (i.e. other websites or services). NANOGAMES.IO cookies enable us
     to keep you signed in to your account throughout your visit and to tailor
     the information displayed on the site to your preferences.
   </p>
   <p class="em">3.What cookies do we use on NANOGAMES.IO?</p>
   <p>
     Below is a list of the main cookies set by NANOGAMES.IO, and what each is used
     for:
   </p>
   <p>_fp - stores browser's fingerprint. Lifetime: forever.</p>
   <p>
     _t - stores timestamp when user firstly visited site in current browsing
     session. Needed for unique visits statistic. Lifetime: browsing session.
   </p>
   <p>
     _r - stores http referrer for current browsing session. Needed in order to
     external track traffic sources. Lifetime: browsing session.
   </p>
   <p>
     _c - stores identifier of affiliate campaign. Needed for affiliate
     statistic. Lifetime: forever.
   </p>
   <p>Cookies set by third parties for wildcard domain: *.NANOGAMES.IO</p>
   <p>Google analytics: _ga, _gat, _gid</p>
   <p>Zendesk：__ zlcmid</p>
   <p>Cloudflare：__ cfuid</p>
   <p>
     Please keep in mind that some browsers (i.e. chrome on mac) keep background
     processes running even if no tabs opened due to this session cookies may
     left set between sessions.
   </p>
   <p>There are also cookies set by third party scripts to their domains.</p>
   <p class="em">4.How can I manage my cookies on NANOGAMES.IO?</p>
   <p>
     If you wish to stop accepting cookies, you can do so through the Privacy
     Settings option in your browser.
   </p>
   <p class="em">5.Personal Data Protection Policy</p>
   <p>
     NANOGAMES.IO’s mission is to keep your Data safe and for this matter we protect
     your data in various ways. We provide our customers with high security
     standards, such as encryption of data in motion over public networks,
     encryption of data in database, auditing standards, Distributed Denial of
     Service mitigations, and a Live Chat available on-site.
   </p>
   <p class="em">6.Server Protection Policy</p>
   <p>All servers have full encryption;</p>
   <p>All backups have encryption;</p>
   <p>Firewalls, VPN Access;</p>
   <p>Access to servers allowed only over VPN;</p>
   <p>All http/s services work over Cloudflare;</p>
   <p>Connections to nodes over VPN;</p>
   <p>SSH port forwarding tunnels;</p>
   <p>Services allowed only over VPN;</p>
   <p>Server have firewall and allowed only SSH port;</p>
   <p>Alerts on critical services.</p>
   <p>Data Breach Notification</p>
   <p>
     When NANOGAMES.IO will be made aware of personal data breaches we will notify
     relevant users in accordance with GDPR timeframes.
   </p>
   <p class="em">7.Data International Transfer</p>
   <p>
     We only disclose personal data to third parties where it is necessary to
     provide the high-quality service or in order to respond lawful requests from
     authorities.
   </p>
   <p>We share the following data to third party systems:</p>
   <p>
     Zendesk Inc. – username and e-mail information is transferred if user sends
     a message to live-chat or sends an e-mail to support mailbox.
   </p>
 
   <h2>Technical issues</h2>
   <p>
     Although we try to do our best, problems could occur now and then. Our team
     will do everything we could to solve your problems as soon as possible. To
     assist you quicker, You can join us by clicking the button above to join the
     telegram group.
   </p>
   <p>If an error occurs, please provide the following information:</p>
   <p>Username</p>
   <p>Date and time of the problem</p>
   <p>Game ID or table name, if any</p>
   <p>Screenshot of the error, if possible</p>
   <p>
     We really appreciate your help and the error report you provided because
     your information report could help us improve.
   </p>
 
   <h2>Collecting and Using Your Personal Data</h2>
   <h2>Types of Data Collected</h2>
   <p><b>Personal Data</b></p>
   <p>
     While using Our Service, We may ask You to provide Us with certain
     personally identifiable information that can be used to contact or identify
     You. Personally identifiable information may include, but is not limited to:
   </p>
   <ul>
     <li>Email address</li>
     <li>First name and last name</li>
     <li>Usage Data</li>
   </ul>
   <p><b>Usage Data</b></p>
   <p>Usage Data is collected automatically when using the Service.</p>
   <p>
     Usage Data may include information such as Your Device's Internet Protocol
     address (e.g. IP address), browser type, browser version, the pages of our
     Service that You visit, the time and date of Your visit, the time spent on
     those pages, unique device identifiers and other diagnostic data.
   </p>
   <p>
     When You access the Service by or through a mobile device, We may collect
     certain information automatically, including, but not limited to, the type
     of mobile device You use, Your mobile device unique ID, the IP address of
     Your mobile device, Your mobile operating system, the type of mobile
     Internet browser You use, unique device identifiers and other diagnostic
     data.
   </p>
   <p>
     We may also collect information that Your browser sends whenever You visit
     our Service or when You access the Service by or through a mobile device.
   </p>
   <h2>Information from Third-Party Social Media Services</h2>
   <p>
     NANOGAMES.IO allows You to create an account and log in to use the Service
     through the following Third-party Social Media Services:
   </p>
   <ul>
     <li>Google</li>
     <li>Facebook</li>
     <li>Telegram</li>
     <li>Metamask</li>
     <li>Web3.0</li>
   </ul>
   <p>
     If You decide to register through or otherwise grant us access to a
     Third-Party Social Media Service, We may collect Personal data that is
     already associated with Your Third-Party Social Media Service's account,
     such as Your name, Your email address, Your activities or Your contact list
     associated with that account.
   </p>
   <p>
     You may also have the option of sharing additional information with the
     NANOGAMES.IO through Your Third-Party Social Media Service's account. If You
     choose to provide such information and Personal Data, during registration or
     otherwise, You are giving NANOGAMES.IO permission to use, share, and store it in
     a manner consistent with this Privacy Policy.
   </p>
   <h2>Delete Personal Data</h2>
   <p>
     You can request to have your personal data deleted if NANOGAMES.IO no longer have
     a legal reason to continue to process or store it. Please note that this
     right is not guaranteed - in the sense that NANOGAMES.IO do not have the ability
     to comply with your request if it is subject to a legal obligation to store
     your data. You can request the deletion of your personal data by sending an
     email to support@nanogames.io
   </p>
 </div></div>

<style>
   
</style>